- hosts: localhost
  vars:
    source_key: "./secrets/id_rsa"
    dest_key: "~/.ssh/id_rsa"
    personal: "~/personal"
    username: "harry"
    pre_tasks:
      - name: Update cache
        apt:
          force_apt_get: true
          update_cache: true
        become: true
  tasks: 
    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/zsh.yml
    - include: tasks/nvim.yml
    - include: tasks/tools.yml
    - include: tasks/lang.yml
    
