- name: Install yadm
  become: true
  apt:
    name: yadm
    force_apt_get: true
  tags:
    - install
    - dotfiles
    - yadm

- name: Clone dotfiles
  shell:
    cmd: yadm clone git@github.com:ujisati/.dotfiles.git -f -b main
  tags:
    - yadm
    - install
    - dotfiles 
