- name: python ppa
  become: true
  shell: add-apt-repository ppa:deadsnakes/ppa -y
  tags:
    - lang   
    - python

- name: python3.11
  become: true
  apt:
    name: python3.11
    force_apt_get: true
  tags:
    - lang
    - python

- name: rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
  tags:
    - lang
    - rust

- name: Install nodejs and npm
  become: true
  apt:
    name: ["nodejs", "npm"]
  tags:
    - lang
    - node
