- name: python ppa
  become: true
  apt_repository:
   repo: ppa:deadsnakes/ppa
   update_cache: True
  tags:
    - install
    - lang   
- name: python3.9
  apt:
    name: python3.9
    force_apt_get: true
  tags:
    - install
    - lang

- name: rust
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y 
  tags:
    - install
    - lang
