- name: Download nvim.appimage
  become: true
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim.appimage
    dest: /usr/local/bin/nvim.appimage
    mode: '0755'
  tags:
    - neovim

- name: Update alternatives for various editor links
  become: true
  command:
    cmd: "update-alternatives --install /usr/bin/{{ item.cmd }} {{ item.cmd }} /usr/local/bin/nvim.appimage 110"
  loop:
    - { cmd: 'ex' }
    - { cmd: 'vi' }
    - { cmd: 'view' }
    - { cmd: 'vim' }
    - { cmd: 'vimdiff' }
  tags:
    - neovim

- name: Backup ~/.config/nvim
  command: mv -f ~/.config/nvim ~/.config/nvim.bak
  ignore_errors: yes
  tags:
    - neovim

- name: Remove ~/.config/nvim
  command: gio trash ~/.config/nvim
  ignore_errors: yes
  tags:
    - neovim
      
- name: Backup ~/.local/share/nvim
  command: mv -f ~/.local/share/nvim ~/.local/share/nvim.bak
  ignore_errors: yes
  tags:
    - neovim

- name: Backup ~/.local/state/nvim
  command: mv -f  ~/.local/state/nvim ~/.local/state/nvim.bak
  ignore_errors: yes
  tags:
    - neovim

- name: Backup ~/.cache/nvim
  command: mv -f ~/.cache/nvim ~/.cache/nvim.bak
  ignore_errors: yes
  tags:
    - neovim

- name: Clone LazyVim/starter repository
  git:
    repo: https://github.com/LazyVim/starter
    dest: ~/.config/nvim
    force: yes
  tags:
    - neovim

- name: Remove Git directory inside ~/.config/nvim
  file:
    path: ~/.config/nvim/.git
    state: absent
  tags:
    - neovim

