- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  apt:
    name: ["neovim"]
  tags:
    - install
    - neovim

- name: Get Packer
  become_user: harry
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
