- name: Neovim ppa
  become: true
  shell: add-apt-repository ppa:neovim-ppa/unstable -y
  tags:
    - neovim

- name: Update cache
  become: true
  apt:
    force_apt_get: true
    update_cache: true

- name: Install neovim
  become: true
  apt:
    name: ["neovim"]
  tags:
    - neovim

# todo: lazyvim
