- name: Neovim ppa
  become: true
  shell: add-apt-repository ppa:neovim-ppa/unstable -y
  tags:
    - install
    - neovim

- name: Update cache
  become: true
  apt:
    force_apt_get: true
    update_cache: true

- name: Install neovim
  become: true
  apt:
    name: ["neovim"]
  tags:
    - install
    - neovim

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
