- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "bat", "tldr", "ripgrep", "xclip"]
  tags:
    - install
    - productivity

- name: tmux plugin manager # Don't forget prefix + I to install plugins in tmux
  become: true
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "~/.tmux/plugins/tpm"
  tags:
    - install
    - productivity


